modLoader = "javafml"
loaderVersion="[1,)"
license="LGPLv3"
showAsResourcePack=false

[[mods]]
modId="sound_physics"
version="${version}"
displayName="Sound Physics Reverberated"
authors="Toni"
description="Fork of Sound Physics that doesn't lag or crash your game."
logoFile="PridefulAnimals-128x.png"

[[dependencies.sound_physics]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"